name: Docker

on:
  push:
    branches:
      - master

  # Nightly to capture latest base image
  schedule:
    - cron: "0 21 * * *"

  # Run tests for any PRs.
  pull_request:

jobs:
  edge:
    name: Build edge image
    if: github.event_name == 'push'
    uses: ./.github/workflows/_docker-build.yml
    with:
      tags: ${{ github.repository }}:edge
    secrets: inherit

  nightly-edge:
    name: Nightly master image
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/_docker-build.yml
    with:
      tags: |
        ${{ github.repository }}:edge
        ${{ github.repository }}:nightly
    secrets: inherit

  find-latest-release:
    name: Find latest release version
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: version
        run: |
          version=$(git describe --tags --abbrev=0 --match 'v*' | sed 's/^v//')
          echo "version=$version" >> $GITHUB_OUTPUT

  nightly-release:
    name: Nightly release image refresh
    needs: find-latest-release
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/_docker-build.yml
    with:
      ref: v${{ needs.find-latest-release.outputs.version }}
      tags: |
        ${{ github.repository }}:${{ needs.find-latest-release.outputs.version }}
        ${{ github.repository }}:latest
    secrets: inherit

  pr:
    name: Build PR image
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_docker-build.yml
    with:
      tags: ${{ github.repository }}:pr-${{ github.event.pull_request.number }}
      push: false
    secrets: inherit
