name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: dockerhub-registry

    runs-on: ubuntu-latest

    steps:
    - name: Trigger deployment
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_type: 'json-extended'
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
